import { observable } from 'mobx';

class DataStore {
    @observable genres = [{code: "Select", genre: "Select"},
    {code: "28", genre: "Action"},
    {code: "12", genre: "Adventure"},
    {code: "16", genre: "Animation"},
    {code: "35", genre: "Comedy"},
    {code: "80", genre: "Crime"},
    {code: "99", genre: "Documentary"},
    {code: "18", genre: "Drama"},
    {code: "10751", genre: "Family"},
    {code: "14", genre: "Fantasy"},
    {code: "36", genre: "History"},
    {code: "27", genre: "Horror"},
    {code: "10402", genre: "Music"},
    {code: "9648", genre: "Mystery"},
    {code: "10749", genre: "Romance"},
    {code: "878", genre: "Science Fiction"},
    {code: "10770", genre: "TV Movie"},
    {code: "54", genre: "Thriller"},
    {code: "10752", genre: "War"},
    {code: "37", genre: "Western"}];

    @observable validNavLinks = '';

    @observable years = [{ code: "Select", year: "Select"},
    { code: "2020", year: "2020"},
    { code: "2019", year: "2019"},
    { code: "2018", year: "2018"},
    { code: "2017", year: "2017"},
    { code: "2016", year: "2016"},
    { code: "2015", year: "2015"},
    { code: "2014", year: "2014"},
    { code: "2013", year: "2013"},
    { code: "2012", year: "2012"},
    { code: "2011", year: "2010"},
    { code: "2009", year: "2009"},
    { code: "2008", year: "2008"},
    { code: "2007", year: "2007"},
    { code: "2006", year: "2006"},
    { code: "2005", year: "2005"},
    { code: "2004", year: "2004"},
    { code: "2003", year: "2003"},
    { code: "2002", year: "2002"},
    { code: "2001", year: "2001"},
    { code: "2000", year: "2000"},
    { code: "1999", year: "1999"},
    { code: "1998", year: "1998"},
    { code: "1997", year: "1997"},
    { code: "1996", year: "1996"},
    { code: "1995", year: "1995"},
    { code: "1994", year: "1994"},
    { code: "1993", year: "1993"},
    { code: "1992", year: "1992"},
    { code: "1991", year: "1991"},
    { code: "1990", year: "1990"},
    { code: "1989", year: "1989"},
    { code: "1988", year: "1988"},
    { code: "1987", year: "1987"},
    { code: "1986", year: "1986"},
    { code: "1985", year: "1985"},
    { code: "1984", year: "1984"},
    { code: "1983", year: "1983"},
    { code: "1982", year: "1982"},
    { code: "1981", year: "1981"},
    { code: "1980", year: "1980"},
    { code: "1979", year: "1979"},
    { code: "1978", year: "1978"},
    { code: "1977", year: "1977"},
    { code: "1976", year: "1976"},
    { code: "1975", year: "1975"},
    { code: "1974", year: "1974"},
    { code: "1973", year: "1973"},
    { code: "1972", year: "1972"},
    { code: "1971", year: "1971"},
    { code: "1970", year: "1970"},
    { code: "1969", year: "1969"},
    { code: "1968", year: "1968"},
    { code: "1967", year: "1967"},
    { code: "1966", year: "1966"},
    { code: "1965", year: "1965"},
    { code: "1964", year: "1964"},
    { code: "1963", year: "1963"},
    { code: "1962", year: "1962"},
    { code: "1961", year: "1961"},
    { code: "1960", year: "1960"},
    { code: "1959", year: "1959"},
    { code: "1958", year: "1958"},
    { code: "1957", year: "1957"},
    { code: "1956", year: "1956"},
    { code: "1955", year: "1955"},
    { code: "1954", year: "1954"},
    { code: "1953", year: "1953"},
    { code: "1952", year: "1952"},
    { code: "1951", year: "1951"},
    { code: "1950", year: "1950"},
    { code: "1949", year: "1949"},
    { code: "1948", year: "1948"},
    { code: "1947", year: "1947"},
    { code: "1946", year: "1946"},
    { code: "1945", year: "1945"},
    { code: "1944", year: "1944"},
    { code: "1943", year: "1943"},
    { code: "1942", year: "1942"},
    { code: "1941", year: "1941"},
    { code: "1940", year: "1940"},
    { code: "1939", year: "1939"},
    { code: "1938", year: "1938"},
    { code: "1937", year: "1937"},
    { code: "1936", year: "1936"},
    { code: "1935", year: "1935"},
    { code: "1934", year: "1934"},
    { code: "1933", year: "1933"},
    { code: "1932", year: "1932"},
    { code: "1931", year: "1931"},
    { code: "1930", year: "1930"},
    { code: "1929", year: "1929"},
    { code: "1928", year: "1928"},
    { code: "1927", year: "1927"},
    { code: "1926", year: "1926"},
    { code: "1925", year: "1925"},
    { code: "1924", year: "1924"},
    { code: "1923", year: "1923"},
    { code: "1922", year: "1922"},
    { code: "1921", year: "1921"},
    { code: "1920", year: "1920"},
    { code: "1919", year: "1919"},
    { code: "1918", year: "1918"},
    { code: "1917", year: "1917"},
    { code: "1916", year: "1916"},
    { code: "1915", year: "1915"},
    { code: "1914", year: "1914"},
    { code: "1913", year: "1913"},
    { code: "1912", year: "1912"},
    { code: "1911", year: "1911"},
    { code: "1910", year: "1910"},
    { code: "1909", year: "1909"},
    { code: "1908", year: "1908"},
    { code: "1907", year: "1907"},
    { code: "1906", year: "1906"},
    { code: "1905", year: "1905"}];

    @observable countries = [{ value: "Select", country: "Select"},
    { value: "United States", country: "United States"},
    { value: "United Kingdom", country: "United Kingdom"},
    { value: "Afghanistan", country: "Afghanistan"},
    { value: "Albania", country: "Albania"},
    { value: "Algeria", country: "Algeria"},
    { value: "American Samoa", country: "American Samoa"},
    { value: "Andorra", country: "Andorra"},
    { value: "Angola", country: "Angola"},
    { value: "Anguilla", country: "Anguilla"},
    { value: "Antarctica", country: "Antarctica"},
    { value: "Antigua and Barbuda", country: "Antigua and Barbuda"},
    { value: "Argentina", country: "Argentina"},
    { value: "Armenia", country: "Armenia"},
    { value: "Aruba", country: "Aruba"},
    { value: "Australia", country: "Australia"},
    { value: "Austria", country: "Austria"},
    { value: "Azerbaijan", country: "Azerbaijan"},
    { value: "Bahamas", country: "Bahamas"},
    { value: "Bahrain", country: "Bahrain"},
    { value: "Bangladesh", country: "Bangladesh"},
    { value: "Barbados", country: "Barbados"},
    { value: "Belarus", country: "Belarus"},
    { value: "Belgium", country: "Belgium"},
    { value: "Belize", country: "Belize"},
    { value: "Benin", country: "Benin"},
    { value: "Bermuda", country: "Bermuda"},
    { value: "Bhutan", country: "Bhutan"},
    { value: "Bolivia", country: "Bolivia"},
    { value: "Bosnia and Herzegovina", country: "Bosnia and Herzegovina"},
    { value: "Botswana", country: "Botswana"},
    { value: "Bouvet Island", country: "Bouvet Island"},
    { value: "Brazil", country: "Brazil"},
    { value: "British Indian Ocean Territory", country: "British Indian Ocean Territory"},
    { value: "Brunei Darussalam", country: "Brunei Darussalam"},
    { value: "Bulgaria", country: "Bulgaria"},
    { value: "Burkina Faso", country: "Burkina Faso"},
    { value: "Burundi", country: "Burundi"},
    { value: "Cambodia", country: "Cambodia"},
    { value: "Cameroon", country: "Cameroon"},
    { value: "Canada", country: "Canada"},
    { value: "Cape Verde", country: "Cape Verde"},
    { value: "Cayman Islands", country: "Cayman Islands"},
    { value: "Central African Republic", country: "Central African Republic"},
    { value: "Chad", country: "Chad"},
    { value: "Chile", country: "Chile"},
    { value: "China", country: "China"},
    { value: "Christmas Island", country: "Christmas Island"},
    { value: "Cocos (Keeling) Islands", country: "Cocos (Keeling) Islands"},
    { value: "Colombia", country: "Colombia"},
    { value: "Comoros", country: "Comoros"},
    { value: "Congo", country: "Congo"},
    { value: "Congo, The Democratic Republic of The", country: "Congo, The Democratic Republic of The"},
    { value: "Cook Islands", country: "Cook Islands"},
    { value: "Costa Rica", country: "Costa Rica"},
    { value: "Cote D'ivoire", country: "Cote D'ivoire"},
    { value: "Croatia", country: "Croatia"},
    { value: "Cuba", country: "Cuba"},
    { value: "Cyprus", country: "Cyprus"},
    { value: "Czech Republic", country: "Czech Republic"},
    { value: "Denmark", country: "Denmark"},
    { value: "Djibouti", country: "Djibouti"},
    { value: "Dominica", country: "Dominica"},
    { value: "Dominican Republic", country: "Dominican Republic"},
    { value: "Ecuador", country: "Ecuador"},
    { value: "Egypt", country: "Egypt"},
    { value: "El Salvador", country: "El Salvador"},
    { value: "Equatorial Guinea", country: "Equatorial Guinea"},
    { value: "Eritrea", country: "Eritrea"},
    { value: "Estonia", country: "Estonia"},
    { value: "Ethiopia", country: "Ethiopia"},
    { value: "Falkland Islands (Malvinas)", country: "Falkland Islands (Malvinas)"},
    { value: "Faroe Islands", country: "Faroe Islands"},
    { value: "Fiji", country: "Fiji"},
    { value: "Finland", country: "Finland"},
    { value: "France", country: "France"},
    { value: "French Guiana", country: "French Guiana"},
    { value: "French Polynesia", country: "French Polynesia"},
    { value: "French Southern Territories", country: "French Southern Territories"},
    { value: "Gabon", country: "Gabon"},
    { value: "Gambia", country: "Gambia"},
    { value: "Georgia", country: "Georgia"},
    { value: "Germany", country: "Germany"},
    { value: "Ghana", country: "Ghana"},
    { value: "Gibraltar", country: "Gibraltar"},
    { value: "Greece", country: "Greece"},
    { value: "Greenland", country: "Greenland"},
    { value: "Grenada", country: "Grenada"},
    { value: "Guadeloupe", country: "Guadeloupe"},
    { value: "Guam", country: "Guam"},
    { value: "Guatemala", country: "Guatemala"},
    { value: "Guinea", country: "Guinea"},
    { value: "Guinea-bissau", country: "Guinea-bissau"},
    { value: "Guyana", country: "Guyana"},
    { value: "Haiti", country: "Haiti"},
    { value: "Heard Island and Mcdonald Islands", country: "Heard Island and Mcdonald Islands"},
    { value: "Holy See (Vatican City State)", country: "Holy See (Vatican City State)"},
    { value: "Honduras", country: "Honduras"},
    { value: "Hong Kong", country: "Hong Kong"},
    { value: "Hungary", country: "Hungary"},
    { value: "Iceland", country: "Iceland"},
    { value: "India", country: "India"},
    { value: "Indonesia", country: "Indonesia"},
    { value: "Iran, Islamic Republic of", country: "Iran, Islamic Republic of"},
    { value: "Iraq", country: "Iraq"},
    { value: "Ireland", country: "Ireland"},
    { value: "Israel", country: "Israel"},
    { value: "Italy", country: "Italy"},
    { value: "Jamaica", country: "Jamaica"},
    { value: "Japan", country: "Japan"},
    { value: "Jordan", country: "Jordan"},
    { value: "Kazakhstan", country: "Kazakhstan"},
    { value: "Kenya", country: "Kenya"},
    { value: "Kiribati", country: "Kiribati"},
    { value: "Korea, Democratic People's Republic of", country: "Korea, Democratic People's Republic of"},
    { value: "Korea, Republic of", country: "Korea, Republic of"},
    { value: "Kuwait", country: "Kuwait"},
    { value: "Kyrgyzstan", country: "Kyrgyzstan"},
    { value: "Lao People's Democratic Republic", country: "Lao People's Democratic Republic"},
    { value: "Latvia", country: "Latvia"},
    { value: "Lebanon", country: "Lebanon"},
    { value: "Lesotho", country: "Lesotho"},
    { value: "Liberia", country: "Liberia"},
    { value: "Libyan Arab Jamahiriya", country: "Libyan Arab Jamahiriya"},
    { value: "Liechtenstein", country: "Liechtenstein"},
    { value: "Lithuania", country: "Lithuania"},
    { value: "Luxembourg", country: "Luxembourg"},
    { value: "Macao", country: "Macao"},
    { value: "North Macedonia", country: "North Macedonia"},
    { value: "Madagascar", country: "Madagascar"},
    { value: "Malawi", country: "Malawi"},
    { value: "Malaysia", country: "Malaysia"},
    { value: "Maldives", country: "Maldives"},
    { value: "Mali", country: "Mali"},
    { value: "Malta", country: "Malta"},
    { value: "Marshall Islands", country: "Marshall Islands"},
    { value: "Martinique", country: "Martinique"},
    { value: "Mauritania", country: "Mauritania"},
    { value: "Mauritius", country: "Mauritius"},
    { value: "Mayotte", country: "Mayotte"},
    { value: "Mexico", country: "Mexico"},
    { value: "Micronesia, Federated States of", country: "Micronesia, Federated States of"},
    { value: "Moldova, Republic of", country: "Moldova, Republic of"},
    { value: "Monaco", country: "Monaco"},
    { value: "Mongolia", country: "Mongolia"},
    { value: "Montserrat", country: "Montserrat"},
    { value: "Morocco", country: "Morocco"},
    { value: "Mozambique", country: "Mozambique"},
    { value: "Myanmar", country: "Myanmar"},
    { value: "Namibia", country: "Namibia"},
    { value: "Nauru", country: "Nauru"},
    { value: "Nepal", country: "Nepal"},
    { value: "Netherlands", country: "Netherlands"},
    { value: "Netherlands Antilles", country: "Netherlands Antilles"},
    { value: "New Caledonia", country: "New Caledonia"},
    { value: "New Zealand", country: "New Zealand"},
    { value: "Nicaragua", country: "Nicaragua"},
    { value: "Niger", country: "Niger"},
    { value: "Nigeria", country: "Nigeria"},
    { value: "Niue", country: "Niue"},
    { value: "Norfolk Island", country: "Norfolk Island"},
    { value: "Northern Mariana Islands", country: "Northern Mariana Islands"},
    { value: "Norway", country: "Norway"},
    { value: "Oman", country: "Oman"},
    { value: "Pakistan", country: "Pakistan"},
    { value: "Palau", country: "Palau"},
    { value: "Palestinian Territory, Occupied", country: "Palestinian Territory, Occupied"},
    { value: "Panama", country: "Panama"},
    { value: "Papua New Guinea", country: "Papua New Guinea"},
    { value: "Paraguay", country: "Paraguay"},
    { value: "Peru", country: "Peru"},
    { value: "Philippines", country: "Philippines"},
    { value: "Pitcairn", country: "Pitcairn"},
    { value: "Poland", country: "Poland"},
    { value: "Portugal", country: "Portugal"},
    { value: "Puerto Rico", country: "Puerto Rico"},
    { value: "Qatar", country: "Qatar"},
    { value: "Reunion", country: "Reunion"},
    { value: "Romania", country: "Romania"},
    { value: "Russian Federation", country: "Russian Federation"},
    { value: "Rwanda", country: "Rwanda"},
    { value: "Saint Helena", country: "Saint Helena"},
    { value: "Saint Kitts and Nevis", country: "Saint Kitts and Nevis"},
    { value: "Saint Lucia", country: "Saint Lucia"},
    { value: "Saint Pierre and Miquelon", country: "Saint Pierre and Miquelon"},
    { value: "Saint Vincent and The Grenadines", country: "Saint Vincent and The Grenadines"},
    { value: "Samoa", country: "Samoa"},
    { value: "San Marino", country: "San Marino"},
    { value: "Sao Tome and Principe", country: "Sao Tome and Principe"},
    { value: "Saudi Arabia", country: "Saudi Arabia"},
    { value: "Senegal", country: "Senegal"},
    { value: "Serbia and Montenegro", country: "Serbia and Montenegro"},
    { value: "Seychelles", country: "Seychelles"},
    { value: "Sierra Leone", country: "Sierra Leone"},
    { value: "Singapore", country: "Singapore"},
    { value: "Slovakia", country: "Slovakia"},
    { value: "Slovenia", country: "Slovenia"},
    { value: "Solomon Islands", country: "Solomon Islands"},
    { value: "Somalia", country: "Somalia"},
    { value: "South Africa", country: "South Africa"},
    { value: "South Georgia and The South Sandwich Islands", country: "South Georgia and The South Sandwich Islands"},
    { value: "Spain", country: "Spain"},
    { value: "Sri Lanka", country: "Sri Lanka"},
    { value: "Sudan", country: "Sudan"},
    { value: "Suriname", country: "Suriname"},
    { value: "Svalbard and Jan Mayen", country: "Svalbard and Jan Mayen"},
    { value: "Swaziland", country: "Swaziland"},
    { value: "Sweden", country: "Sweden"},
    { value: "Switzerland", country: "Switzerland"},
    { value: "Syrian Arab Republic", country: "Syrian Arab Republic"},
    { value: "Taiwan, Province of China", country: "Taiwan, Province of China"},
    { value: "Tajikistan", country: "Tajikistan"},
    { value: "Tanzania United Republic of", country: "Tanzania United Republic of"},
    { value: "Thailand", country: "Thailand"},
    { value: "Timor-leste", country: "Timor-leste"},
    { value: "Togo", country: "Togo"},
    { value: "Tokelau", country: "Tokelau"},
    { value: "Tonga", country: "Tonga"},
    { value: "Trinidad and Tobago", country: "Trinidad and Tobago"},
    { value: "Tunisia", country: "Tunisia"},
    { value: "Turkey", country: "Turkey"},
    { value: "Turkmenistan", country: "Turkmenistan"},
    { value: "Turks and Caicos Islands", country: "Turks and Caicos Islands"},
    { value: "Tuvalu", country: "Tuvalu"},
    { value: "Uganda", country: "Uganda"},
    { value: "Ukraine", country: "Ukraine"},
    { value: "United Arab Emirates", country: "United Arab Emirates"},
    { value: "United Kingdom", country: "United Kingdom"},
    { value: "United States", country: "United States"},
    { value: "United States Minor Outlying Islands", country: "United States Minor Outlying Islands"},
    { value: "Uruguay", country: "Uruguay"},
    { value: "Uzbekistan", country: "Uzbekistan"},
    { value: "Vanuatu", country: "Vanuatu"},
    { value: "Venezuela", country: "Venezuela"},
    { value: "Viet Nam", country: "Viet Nam"},
    { value: "Virgin Islands, British", country: "Virgin Islands, British"},
    { value: "Virgin Islands, U.S.", country: "Virgin Islands, U.S."},
    { value: "Wallis and Futuna", country: "Wallis and Futuna"},
    { value: "Western Sahara", country: "Western Sahara"},
    { value: "Yemen", country: "Yemen"},
    { value: "Zambia", country: "Zambia"},
    { value: "Zimbabwe", country: "Zimbabwe"}];

    // This will be replaced by an async action which updates the local store of movie info
    // This will be done such that data is fetched > data is stored locally > data is written to DOM
    // once DOM has new data async is performed again to fetch next page > store locally > write to DOM 
    @observable testMovieData = {
        "page": 1,
        "total_results": 10000,
        "total_pages": 500,
        "results": [
            {
                "popularity": 492.069,
                "vote_count": 3023,
                "video": false,
                "poster_path": "/xJUILftRf6TJxloOgrilOTJfeOn.jpg",
                "id": 419704,
                "adult": false,
                "backdrop_path": "/5BwqwxMEjeFtdknRV792Svo0K1v.jpg",
                "original_language": "en",
                "original_title": "Ad Astra",
                "genre_ids": [
                    18,
                    878
                ],
                "title": "Ad Astra",
                "vote_average": 6,
                "overview": "The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.",
                "release_date": "2019-09-17"
            },
            {
                "popularity": 312.399,
                "vote_count": 6802,
                "video": false,
                "poster_path": "/y6O8fBTRMvqs6wYqunXhONbJRk2.jpg",
                "id": 56292,
                "adult": false,
                "backdrop_path": "/zNyNPn86myH5Ix1demDa5dfYDao.jpg",
                "original_language": "en",
                "original_title": "Mission: Impossible - Ghost Protocol",
                "genre_ids": [
                    28,
                    12,
                    53
                ],
                "title": "Mission: Impossible - Ghost Protocol",
                "vote_average": 7,
                "overview": "Ethan Hunt and his team are racing against time to track down a dangerous terrorist named Hendricks, who has gained access to Russian nuclear launch codes and is planning a strike on the United States. An attempt to stop him ends in an explosion causing severe destruction to the Kremlin and the IMF to be implicated in the bombing, forcing the President to disavow them. No longer being aided by the government, Ethan and his team chase Hendricks around the globe, although they might still be too late to stop a disaster.",
                "release_date": "2011-12-07"
            },
            {
                "popularity": 231.061,
                "vote_count": 204,
                "video": false,
                "poster_path": "/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg",
                "id": 446893,
                "adult": false,
                "backdrop_path": "/qsxhnirlp7y4Ae9bd11oYJSX59j.jpg",
                "original_language": "en",
                "original_title": "Trolls World Tour",
                "genre_ids": [
                    12,
                    16,
                    35,
                    14,
                    10402,
                    10751
                ],
                "title": "Trolls World Tour",
                "vote_average": 7.7,
                "overview": "Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land in danger, Poppy, Branch, and their band of friends must embark on an epic quest to create harmony among the feuding Trolls to unite them against certain doom.",
                "release_date": "2020-03-12"
            },
            {
                "popularity": 217.825,
                "vote_count": 2723,
                "video": false,
                "poster_path": "/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
                "id": 454626,
                "adult": false,
                "backdrop_path": "/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
                "original_language": "en",
                "original_title": "Sonic the Hedgehog",
                "genre_ids": [
                    28,
                    35,
                    878,
                    10751
                ],
                "title": "Sonic the Hedgehog",
                "vote_average": 7.6,
                "overview": "Based on the global blockbuster videogame franchise from Sega, Sonic the Hedgehog tells the story of the world’s speediest hedgehog as he embraces his new home on Earth. In this live-action adventure comedy, Sonic and his new best friend team up to defend the planet from the evil genius Dr. Robotnik and his plans for world domination.",
                "release_date": "2020-02-12"
            },
            {
                "popularity": 202.314,
                "vote_count": 3073,
                "video": false,
                "poster_path": "/y95lQLnuNKdPAzw9F9Ab8kJ80c3.jpg",
                "id": 38700,
                "adult": false,
                "backdrop_path": "/upUy2QhMZEmtypPW3PdieKLAHxh.jpg",
                "original_language": "en",
                "original_title": "Bad Boys for Life",
                "genre_ids": [
                    28,
                    80,
                    53
                ],
                "title": "Bad Boys for Life",
                "vote_average": 7.2,
                "overview": "Marcus and Mike are forced to confront new threats, career changes, and midlife crises as they join the newly created elite team AMMO of the Miami police department to take down the ruthless Armando Armas, the vicious leader of a Miami drug cartel.",
                "release_date": "2020-01-15"
            },
            {
                "popularity": 196.882,
                "vote_count": 2767,
                "video": false,
                "poster_path": "/hba8zREJpP1AYhaXgb2oJLQeO0K.jpg",
                "id": 47971,
                "adult": false,
                "backdrop_path": "/7VSpa8RSjvJe1vDgNWbT3IxT27d.jpg",
                "original_language": "en",
                "original_title": "xXx: Return of Xander Cage",
                "genre_ids": [
                    28,
                    12,
                    80
                ],
                "title": "xXx: Return of Xander Cage",
                "vote_average": 5.6,
                "overview": "Extreme athlete turned government operative Xander Cage comes out of self-imposed exile, thought to be long dead, and is set on a collision course with deadly alpha warrior Xiang and his team in a race to recover a sinister and seemingly unstoppable weapon known as Pandora's Box. Recruiting an all-new group of thrill-seeking cohorts, Xander finds himself enmeshed in a deadly conspiracy that points to collusion at the highest levels of world governments.",
                "release_date": "2017-01-13"
            },
            {
                "popularity": 181.363,
                "vote_count": 3003,
                "video": false,
                "poster_path": "/h4VB6m0RwcicVEZvzftYZyKXs6K.jpg",
                "id": 495764,
                "adult": false,
                "backdrop_path": "/uozb2VeD87YmhoUP1RrGWfzuCrr.jpg",
                "original_language": "en",
                "original_title": "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
                "genre_ids": [
                    28,
                    35,
                    80
                ],
                "title": "Birds of Prey (and the Fantabulous Emancipation of One Harley Quinn)",
                "vote_average": 7.2,
                "overview": "Harley Quinn joins forces with a singer, an assassin and a police detective to help a young girl who had a hit placed on her after she stole a rare diamond from a crime lord.",
                "release_date": "2020-02-05"
            },
            {
                "popularity": 171.218,
                "vote_count": 3992,
                "video": false,
                "poster_path": "/db32LaOibwEliAmSL2jjDF6oDdj.jpg",
                "id": 181812,
                "adult": false,
                "backdrop_path": "/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg",
                "original_language": "en",
                "original_title": "Star Wars: The Rise of Skywalker",
                "genre_ids": [
                    28,
                    12,
                    878
                ],
                "title": "Star Wars: The Rise of Skywalker",
                "vote_average": 6.5,
                "overview": "The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.",
                "release_date": "2019-12-18"
            },
            {
                "popularity": 163.712,
                "vote_count": 1642,
                "video": false,
                "poster_path": "/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
                "id": 338762,
                "adult": false,
                "backdrop_path": "/ocUrMYbdjknu2TwzMHKT9PBBQRw.jpg",
                "original_language": "en",
                "original_title": "Bloodshot",
                "genre_ids": [
                    28,
                    878
                ],
                "title": "Bloodshot",
                "vote_average": 7.2,
                "overview": "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
                "release_date": "2020-03-05"
            },
            {
                "popularity": 161.601,
                "vote_count": 493,
                "video": false,
                "poster_path": "/hrfh9uVxcTu21vVxDs40l0CDWGW.jpg",
                "id": 414419,
                "adult": false,
                "backdrop_path": null,
                "original_language": "en",
                "original_title": "Kill Bill: The Whole Bloody Affair",
                "genre_ids": [
                    28,
                    80
                ],
                "title": "Kill Bill: The Whole Bloody Affair",
                "vote_average": 8,
                "overview": "Kill Bill: The Whole Bloody Affair is a complete edit of the two-part martial arts action films Kill Bill: Vol. 1 and Kill Bill: Vol. 2. The film was originally scheduled to be released as one part. However, due to the film's over 4 hour running time, it was split into two parts.",
                "release_date": "2011-03-28"
            },
            {
                "popularity": 144.46,
                "vote_count": 67,
                "video": false,
                "poster_path": "/4VlXER3FImHeFuUjBShFamhIp9M.jpg",
                "id": 664767,
                "adult": false,
                "backdrop_path": "/vw3zNfzvnVNF7nIjpiEgcdznfeC.jpg",
                "original_language": "en",
                "original_title": "Mortal Kombat Legends: Scorpion’s Revenge",
                "genre_ids": [
                    28,
                    12,
                    16,
                    14
                ],
                "title": "Mortal Kombat Legends: Scorpion’s Revenge",
                "vote_average": 8.4,
                "overview": "After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.",
                "release_date": "2020-04-12"
            },
            {
                "popularity": 123.294,
                "id": 614375,
                "video": false,
                "vote_count": 8,
                "vote_average": 6.2,
                "title": "F#*@BOIS",
                "release_date": "2019-08-02",
                "original_language": "tl",
                "original_title": "F#*@BOIS",
                "genre_ids": [
                    18
                ],
                "backdrop_path": null,
                "adult": false,
                "overview": "Ace, 23, and Miko, 17, desperately want to become famous actors but it seems the Universe has a different plan for their lives.",
                "poster_path": "/hjOX3eTRR37WdsTMXOcD0gF9BA7.jpg"
            },
            {
                "popularity": 121.779,
                "vote_count": 3201,
                "video": false,
                "poster_path": "/bB42KDdfWkOvmzmYkmK58ZlCa9P.jpg",
                "id": 512200,
                "adult": false,
                "backdrop_path": "/oLma4sWjqlXVr0E3jpaXQCytuG9.jpg",
                "original_language": "en",
                "original_title": "Jumanji: The Next Level",
                "genre_ids": [
                    12,
                    35,
                    14
                ],
                "title": "Jumanji: The Next Level",
                "vote_average": 6.9,
                "overview": "As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.",
                "release_date": "2019-12-04"
            },
            {
                "popularity": 121.31,
                "vote_count": 875,
                "video": false,
                "poster_path": "/jtrhTYB7xSrJxR1vusu99nvnZ1g.jpg",
                "id": 522627,
                "adult": false,
                "backdrop_path": "/tintsaQ0WLzZsTMkTiqtMB3rfc8.jpg",
                "original_language": "en",
                "original_title": "The Gentlemen",
                "genre_ids": [
                    28,
                    35,
                    80
                ],
                "title": "The Gentlemen",
                "vote_average": 7.8,
                "overview": "American expat Mickey Pearson has built a highly profitable marijuana empire in London. When word gets out that he’s looking to cash out of the business forever it triggers plots, schemes, bribery and blackmail in an attempt to steal his domain out from under him.",
                "release_date": "2020-01-01"
            },
            {
                "popularity": 116.342,
                "id": 443791,
                "video": false,
                "vote_count": 728,
                "vote_average": 6.5,
                "title": "Underwater",
                "release_date": "2020-01-08",
                "original_language": "en",
                "original_title": "Underwater",
                "genre_ids": [
                    27,
                    878,
                    28,
                    53
                ],
                "backdrop_path": "/fYPiQewg7ogbzro2XcCTACSB2KC.jpg",
                "adult": false,
                "overview": "After an earthquake destroys their underwater station, six researchers must navigate two miles along the dangerous, unknown depths of the ocean floor to make it to safety in a race against time.",
                "poster_path": "/gzlbb3yeVISpQ3REd3Ga1scWGTU.jpg"
            },
            {
                "popularity": 108.44,
                "vote_count": 9067,
                "video": false,
                "poster_path": "/qa6HCwP4Z15l3hpsASz3auugEW6.jpg",
                "id": 920,
                "adult": false,
                "backdrop_path": "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
                "original_language": "en",
                "original_title": "Cars",
                "genre_ids": [
                    12,
                    16,
                    35,
                    10751
                ],
                "title": "Cars",
                "vote_average": 6.8,
                "overview": "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
                "release_date": "2006-06-08"
            },
            {
                "popularity": 106.644,
                "vote_count": 11417,
                "video": false,
                "poster_path": "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                "id": 475557,
                "adult": false,
                "backdrop_path": "/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg",
                "original_language": "en",
                "original_title": "Joker",
                "genre_ids": [
                    80,
                    18,
                    53
                ],
                "title": "Joker",
                "vote_average": 8.2,
                "overview": "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
                "release_date": "2019-10-02"
            },
            {
                "popularity": 101.414,
                "vote_count": 2341,
                "video": false,
                "poster_path": "/8ZX18L5m6rH5viSYpRnTSbb9eXh.jpg",
                "id": 619264,
                "adult": false,
                "backdrop_path": "/3tkDMNfM2YuIAJlvGO6rfIzAnfG.jpg",
                "original_language": "es",
                "original_title": "El hoyo",
                "genre_ids": [
                    18,
                    878
                ],
                "title": "The Platform",
                "vote_average": 7.1,
                "overview": "A mysterious place, an indescribable prison, a deep hole. An unknown number of levels. Two inmates living on each level. A descending platform containing food for all of them. An inhuman fight for survival, but also an opportunity for solidarity…",
                "release_date": "2019-11-08"
            },
            {
                "popularity": 99.18,
                "vote_count": 6384,
                "video": false,
                "poster_path": "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                "id": 496243,
                "adult": false,
                "backdrop_path": "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
                "original_language": "ko",
                "original_title": "기생충",
                "genre_ids": [
                    35,
                    18,
                    53
                ],
                "title": "Parasite",
                "vote_average": 8.5,
                "overview": "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
                "release_date": "2019-05-30"
            },
            {
                "popularity": 98.165,
                "vote_count": 31,
                "video": false,
                "poster_path": "/b4thKm1P0F1SYeL11uyVAlGhzR6.jpg",
                "id": 625489,
                "adult": false,
                "backdrop_path": "/q1Z6dufl5BFvtyfIscnQoFaUiW8.jpg",
                "original_language": "tr",
                "original_title": "Recep İvedik 6",
                "genre_ids": [
                    35
                ],
                "title": "Recep İvedik 6",
                "vote_average": 5.1,
                "overview": "",
                "release_date": "2019-11-07"
            }
        ]
    };

    @observable temporaryAccounts = [];

    @observable comments = [
        {
            title: "testy",
            title_id: 419704,
            user: "tac",
            posted: 1587404643400,
            body: "testy test test test"
        }
    ];
}

export default new DataStore();