import { observable } from 'mobx';

class DataStore {
    @observable genres = [{code: "Select", genre: "Select"},
    {code: "28", genre: "Action"},
    {code: "12", genre: "Adventure"},
    {code: "16", genre: "Animation"},
    {code: "35", genre: "Comedy"},
    {code: "80", genre: "Crime"},
    {code: "99", genre: "Documentary"},
    {code: "18", genre: "Drama"},
    {code: "10751", genre: "Family"},
    {code: "14", genre: "Fantasy"},
    {code: "36", genre: "History"},
    {code: "27", genre: "Horror"},
    {code: "10402", genre: "Music"},
    {code: "9648", genre: "Mystery"},
    {code: "10749", genre: "Romance"},
    {code: "878", genre: "Science Fiction"},
    {code: "10770", genre: "TV Movie"},
    {code: "54", genre: "Thriller"},
    {code: "10752", genre: "War"},
    {code: "37", genre: "Western"}];

    @observable validNavLinks = [];

    @observable years = [{ code: "Select", year: "Select"},
    { code: "2020", year: "2020"},
    { code: "2019", year: "2019"},
    { code: "2018", year: "2018"},
    { code: "2017", year: "2017"},
    { code: "2016", year: "2016"},
    { code: "2015", year: "2015"},
    { code: "2014", year: "2014"},
    { code: "2013", year: "2013"},
    { code: "2012", year: "2012"},
    { code: "2011", year: "2010"},
    { code: "2009", year: "2009"},
    { code: "2008", year: "2008"},
    { code: "2007", year: "2007"},
    { code: "2006", year: "2006"},
    { code: "2005", year: "2005"},
    { code: "2004", year: "2004"},
    { code: "2003", year: "2003"},
    { code: "2002", year: "2002"},
    { code: "2001", year: "2001"},
    { code: "2000", year: "2000"},
    { code: "1999", year: "1999"},
    { code: "1998", year: "1998"},
    { code: "1997", year: "1997"},
    { code: "1996", year: "1996"},
    { code: "1995", year: "1995"},
    { code: "1994", year: "1994"},
    { code: "1993", year: "1993"},
    { code: "1992", year: "1992"},
    { code: "1991", year: "1991"},
    { code: "1990", year: "1990"},
    { code: "1989", year: "1989"},
    { code: "1988", year: "1988"},
    { code: "1987", year: "1987"},
    { code: "1986", year: "1986"},
    { code: "1985", year: "1985"},
    { code: "1984", year: "1984"},
    { code: "1983", year: "1983"},
    { code: "1982", year: "1982"},
    { code: "1981", year: "1981"},
    { code: "1980", year: "1980"},
    { code: "1979", year: "1979"},
    { code: "1978", year: "1978"},
    { code: "1977", year: "1977"},
    { code: "1976", year: "1976"},
    { code: "1975", year: "1975"},
    { code: "1974", year: "1974"},
    { code: "1973", year: "1973"},
    { code: "1972", year: "1972"},
    { code: "1971", year: "1971"},
    { code: "1970", year: "1970"},
    { code: "1969", year: "1969"},
    { code: "1968", year: "1968"},
    { code: "1967", year: "1967"},
    { code: "1966", year: "1966"},
    { code: "1965", year: "1965"},
    { code: "1964", year: "1964"},
    { code: "1963", year: "1963"},
    { code: "1962", year: "1962"},
    { code: "1961", year: "1961"},
    { code: "1960", year: "1960"},
    { code: "1959", year: "1959"},
    { code: "1958", year: "1958"},
    { code: "1957", year: "1957"},
    { code: "1956", year: "1956"},
    { code: "1955", year: "1955"},
    { code: "1954", year: "1954"},
    { code: "1953", year: "1953"},
    { code: "1952", year: "1952"},
    { code: "1951", year: "1951"},
    { code: "1950", year: "1950"},
    { code: "1949", year: "1949"},
    { code: "1948", year: "1948"},
    { code: "1947", year: "1947"},
    { code: "1946", year: "1946"},
    { code: "1945", year: "1945"},
    { code: "1944", year: "1944"},
    { code: "1943", year: "1943"},
    { code: "1942", year: "1942"},
    { code: "1941", year: "1941"},
    { code: "1940", year: "1940"},
    { code: "1939", year: "1939"},
    { code: "1938", year: "1938"},
    { code: "1937", year: "1937"},
    { code: "1936", year: "1936"},
    { code: "1935", year: "1935"},
    { code: "1934", year: "1934"},
    { code: "1933", year: "1933"},
    { code: "1932", year: "1932"},
    { code: "1931", year: "1931"},
    { code: "1930", year: "1930"},
    { code: "1929", year: "1929"},
    { code: "1928", year: "1928"},
    { code: "1927", year: "1927"},
    { code: "1926", year: "1926"},
    { code: "1925", year: "1925"},
    { code: "1924", year: "1924"},
    { code: "1923", year: "1923"},
    { code: "1922", year: "1922"},
    { code: "1921", year: "1921"},
    { code: "1920", year: "1920"},
    { code: "1919", year: "1919"},
    { code: "1918", year: "1918"},
    { code: "1917", year: "1917"},
    { code: "1916", year: "1916"},
    { code: "1915", year: "1915"},
    { code: "1914", year: "1914"},
    { code: "1913", year: "1913"},
    { code: "1912", year: "1912"},
    { code: "1911", year: "1911"},
    { code: "1910", year: "1910"},
    { code: "1909", year: "1909"},
    { code: "1908", year: "1908"},
    { code: "1907", year: "1907"},
    { code: "1906", year: "1906"},
    { code: "1905", year: "1905"}];

    @observable countries = [{ value: "Select", country: "Select"},
    { value: "United States", country: "United States"},
    { value: "United Kingdom", country: "United Kingdom"},
    { value: "Afghanistan", country: "Afghanistan"},
    { value: "Albania", country: "Albania"},
    { value: "Algeria", country: "Algeria"},
    { value: "American Samoa", country: "American Samoa"},
    { value: "Andorra", country: "Andorra"},
    { value: "Angola", country: "Angola"},
    { value: "Anguilla", country: "Anguilla"},
    { value: "Antarctica", country: "Antarctica"},
    { value: "Antigua and Barbuda", country: "Antigua and Barbuda"},
    { value: "Argentina", country: "Argentina"},
    { value: "Armenia", country: "Armenia"},
    { value: "Aruba", country: "Aruba"},
    { value: "Australia", country: "Australia"},
    { value: "Austria", country: "Austria"},
    { value: "Azerbaijan", country: "Azerbaijan"},
    { value: "Bahamas", country: "Bahamas"},
    { value: "Bahrain", country: "Bahrain"},
    { value: "Bangladesh", country: "Bangladesh"},
    { value: "Barbados", country: "Barbados"},
    { value: "Belarus", country: "Belarus"},
    { value: "Belgium", country: "Belgium"},
    { value: "Belize", country: "Belize"},
    { value: "Benin", country: "Benin"},
    { value: "Bermuda", country: "Bermuda"},
    { value: "Bhutan", country: "Bhutan"},
    { value: "Bolivia", country: "Bolivia"},
    { value: "Bosnia and Herzegovina", country: "Bosnia and Herzegovina"},
    { value: "Botswana", country: "Botswana"},
    { value: "Bouvet Island", country: "Bouvet Island"},
    { value: "Brazil", country: "Brazil"},
    { value: "British Indian Ocean Territory", country: "British Indian Ocean Territory"},
    { value: "Brunei Darussalam", country: "Brunei Darussalam"},
    { value: "Bulgaria", country: "Bulgaria"},
    { value: "Burkina Faso", country: "Burkina Faso"},
    { value: "Burundi", country: "Burundi"},
    { value: "Cambodia", country: "Cambodia"},
    { value: "Cameroon", country: "Cameroon"},
    { value: "Canada", country: "Canada"},
    { value: "Cape Verde", country: "Cape Verde"},
    { value: "Cayman Islands", country: "Cayman Islands"},
    { value: "Central African Republic", country: "Central African Republic"},
    { value: "Chad", country: "Chad"},
    { value: "Chile", country: "Chile"},
    { value: "China", country: "China"},
    { value: "Christmas Island", country: "Christmas Island"},
    { value: "Cocos (Keeling) Islands", country: "Cocos (Keeling) Islands"},
    { value: "Colombia", country: "Colombia"},
    { value: "Comoros", country: "Comoros"},
    { value: "Congo", country: "Congo"},
    { value: "Congo, The Democratic Republic of The", country: "Congo, The Democratic Republic of The"},
    { value: "Cook Islands", country: "Cook Islands"},
    { value: "Costa Rica", country: "Costa Rica"},
    { value: "Cote D'ivoire", country: "Cote D'ivoire"},
    { value: "Croatia", country: "Croatia"},
    { value: "Cuba", country: "Cuba"},
    { value: "Cyprus", country: "Cyprus"},
    { value: "Czech Republic", country: "Czech Republic"},
    { value: "Denmark", country: "Denmark"},
    { value: "Djibouti", country: "Djibouti"},
    { value: "Dominica", country: "Dominica"},
    { value: "Dominican Republic", country: "Dominican Republic"},
    { value: "Ecuador", country: "Ecuador"},
    { value: "Egypt", country: "Egypt"},
    { value: "El Salvador", country: "El Salvador"},
    { value: "Equatorial Guinea", country: "Equatorial Guinea"},
    { value: "Eritrea", country: "Eritrea"},
    { value: "Estonia", country: "Estonia"},
    { value: "Ethiopia", country: "Ethiopia"},
    { value: "Falkland Islands (Malvinas)", country: "Falkland Islands (Malvinas)"},
    { value: "Faroe Islands", country: "Faroe Islands"},
    { value: "Fiji", country: "Fiji"},
    { value: "Finland", country: "Finland"},
    { value: "France", country: "France"},
    { value: "French Guiana", country: "French Guiana"},
    { value: "French Polynesia", country: "French Polynesia"},
    { value: "French Southern Territories", country: "French Southern Territories"},
    { value: "Gabon", country: "Gabon"},
    { value: "Gambia", country: "Gambia"},
    { value: "Georgia", country: "Georgia"},
    { value: "Germany", country: "Germany"},
    { value: "Ghana", country: "Ghana"},
    { value: "Gibraltar", country: "Gibraltar"},
    { value: "Greece", country: "Greece"},
    { value: "Greenland", country: "Greenland"},
    { value: "Grenada", country: "Grenada"},
    { value: "Guadeloupe", country: "Guadeloupe"},
    { value: "Guam", country: "Guam"},
    { value: "Guatemala", country: "Guatemala"},
    { value: "Guinea", country: "Guinea"},
    { value: "Guinea-bissau", country: "Guinea-bissau"},
    { value: "Guyana", country: "Guyana"},
    { value: "Haiti", country: "Haiti"},
    { value: "Heard Island and Mcdonald Islands", country: "Heard Island and Mcdonald Islands"},
    { value: "Holy See (Vatican City State)", country: "Holy See (Vatican City State)"},
    { value: "Honduras", country: "Honduras"},
    { value: "Hong Kong", country: "Hong Kong"},
    { value: "Hungary", country: "Hungary"},
    { value: "Iceland", country: "Iceland"},
    { value: "India", country: "India"},
    { value: "Indonesia", country: "Indonesia"},
    { value: "Iran, Islamic Republic of", country: "Iran, Islamic Republic of"},
    { value: "Iraq", country: "Iraq"},
    { value: "Ireland", country: "Ireland"},
    { value: "Israel", country: "Israel"},
    { value: "Italy", country: "Italy"},
    { value: "Jamaica", country: "Jamaica"},
    { value: "Japan", country: "Japan"},
    { value: "Jordan", country: "Jordan"},
    { value: "Kazakhstan", country: "Kazakhstan"},
    { value: "Kenya", country: "Kenya"},
    { value: "Kiribati", country: "Kiribati"},
    { value: "Korea, Democratic People's Republic of", country: "Korea, Democratic People's Republic of"},
    { value: "Korea, Republic of", country: "Korea, Republic of"},
    { value: "Kuwait", country: "Kuwait"},
    { value: "Kyrgyzstan", country: "Kyrgyzstan"},
    { value: "Lao People's Democratic Republic", country: "Lao People's Democratic Republic"},
    { value: "Latvia", country: "Latvia"},
    { value: "Lebanon", country: "Lebanon"},
    { value: "Lesotho", country: "Lesotho"},
    { value: "Liberia", country: "Liberia"},
    { value: "Libyan Arab Jamahiriya", country: "Libyan Arab Jamahiriya"},
    { value: "Liechtenstein", country: "Liechtenstein"},
    { value: "Lithuania", country: "Lithuania"},
    { value: "Luxembourg", country: "Luxembourg"},
    { value: "Macao", country: "Macao"},
    { value: "North Macedonia", country: "North Macedonia"},
    { value: "Madagascar", country: "Madagascar"},
    { value: "Malawi", country: "Malawi"},
    { value: "Malaysia", country: "Malaysia"},
    { value: "Maldives", country: "Maldives"},
    { value: "Mali", country: "Mali"},
    { value: "Malta", country: "Malta"},
    { value: "Marshall Islands", country: "Marshall Islands"},
    { value: "Martinique", country: "Martinique"},
    { value: "Mauritania", country: "Mauritania"},
    { value: "Mauritius", country: "Mauritius"},
    { value: "Mayotte", country: "Mayotte"},
    { value: "Mexico", country: "Mexico"},
    { value: "Micronesia, Federated States of", country: "Micronesia, Federated States of"},
    { value: "Moldova, Republic of", country: "Moldova, Republic of"},
    { value: "Monaco", country: "Monaco"},
    { value: "Mongolia", country: "Mongolia"},
    { value: "Montserrat", country: "Montserrat"},
    { value: "Morocco", country: "Morocco"},
    { value: "Mozambique", country: "Mozambique"},
    { value: "Myanmar", country: "Myanmar"},
    { value: "Namibia", country: "Namibia"},
    { value: "Nauru", country: "Nauru"},
    { value: "Nepal", country: "Nepal"},
    { value: "Netherlands", country: "Netherlands"},
    { value: "Netherlands Antilles", country: "Netherlands Antilles"},
    { value: "New Caledonia", country: "New Caledonia"},
    { value: "New Zealand", country: "New Zealand"},
    { value: "Nicaragua", country: "Nicaragua"},
    { value: "Niger", country: "Niger"},
    { value: "Nigeria", country: "Nigeria"},
    { value: "Niue", country: "Niue"},
    { value: "Norfolk Island", country: "Norfolk Island"},
    { value: "Northern Mariana Islands", country: "Northern Mariana Islands"},
    { value: "Norway", country: "Norway"},
    { value: "Oman", country: "Oman"},
    { value: "Pakistan", country: "Pakistan"},
    { value: "Palau", country: "Palau"},
    { value: "Palestinian Territory, Occupied", country: "Palestinian Territory, Occupied"},
    { value: "Panama", country: "Panama"},
    { value: "Papua New Guinea", country: "Papua New Guinea"},
    { value: "Paraguay", country: "Paraguay"},
    { value: "Peru", country: "Peru"},
    { value: "Philippines", country: "Philippines"},
    { value: "Pitcairn", country: "Pitcairn"},
    { value: "Poland", country: "Poland"},
    { value: "Portugal", country: "Portugal"},
    { value: "Puerto Rico", country: "Puerto Rico"},
    { value: "Qatar", country: "Qatar"},
    { value: "Reunion", country: "Reunion"},
    { value: "Romania", country: "Romania"},
    { value: "Russian Federation", country: "Russian Federation"},
    { value: "Rwanda", country: "Rwanda"},
    { value: "Saint Helena", country: "Saint Helena"},
    { value: "Saint Kitts and Nevis", country: "Saint Kitts and Nevis"},
    { value: "Saint Lucia", country: "Saint Lucia"},
    { value: "Saint Pierre and Miquelon", country: "Saint Pierre and Miquelon"},
    { value: "Saint Vincent and The Grenadines", country: "Saint Vincent and The Grenadines"},
    { value: "Samoa", country: "Samoa"},
    { value: "San Marino", country: "San Marino"},
    { value: "Sao Tome and Principe", country: "Sao Tome and Principe"},
    { value: "Saudi Arabia", country: "Saudi Arabia"},
    { value: "Senegal", country: "Senegal"},
    { value: "Serbia and Montenegro", country: "Serbia and Montenegro"},
    { value: "Seychelles", country: "Seychelles"},
    { value: "Sierra Leone", country: "Sierra Leone"},
    { value: "Singapore", country: "Singapore"},
    { value: "Slovakia", country: "Slovakia"},
    { value: "Slovenia", country: "Slovenia"},
    { value: "Solomon Islands", country: "Solomon Islands"},
    { value: "Somalia", country: "Somalia"},
    { value: "South Africa", country: "South Africa"},
    { value: "South Georgia and The South Sandwich Islands", country: "South Georgia and The South Sandwich Islands"},
    { value: "Spain", country: "Spain"},
    { value: "Sri Lanka", country: "Sri Lanka"},
    { value: "Sudan", country: "Sudan"},
    { value: "Suriname", country: "Suriname"},
    { value: "Svalbard and Jan Mayen", country: "Svalbard and Jan Mayen"},
    { value: "Swaziland", country: "Swaziland"},
    { value: "Sweden", country: "Sweden"},
    { value: "Switzerland", country: "Switzerland"},
    { value: "Syrian Arab Republic", country: "Syrian Arab Republic"},
    { value: "Taiwan, Province of China", country: "Taiwan, Province of China"},
    { value: "Tajikistan", country: "Tajikistan"},
    { value: "Tanzania United Republic of", country: "Tanzania United Republic of"},
    { value: "Thailand", country: "Thailand"},
    { value: "Timor-leste", country: "Timor-leste"},
    { value: "Togo", country: "Togo"},
    { value: "Tokelau", country: "Tokelau"},
    { value: "Tonga", country: "Tonga"},
    { value: "Trinidad and Tobago", country: "Trinidad and Tobago"},
    { value: "Tunisia", country: "Tunisia"},
    { value: "Turkey", country: "Turkey"},
    { value: "Turkmenistan", country: "Turkmenistan"},
    { value: "Turks and Caicos Islands", country: "Turks and Caicos Islands"},
    { value: "Tuvalu", country: "Tuvalu"},
    { value: "Uganda", country: "Uganda"},
    { value: "Ukraine", country: "Ukraine"},
    { value: "United Arab Emirates", country: "United Arab Emirates"},
    { value: "United Kingdom", country: "United Kingdom"},
    { value: "United States", country: "United States"},
    { value: "United States Minor Outlying Islands", country: "United States Minor Outlying Islands"},
    { value: "Uruguay", country: "Uruguay"},
    { value: "Uzbekistan", country: "Uzbekistan"},
    { value: "Vanuatu", country: "Vanuatu"},
    { value: "Venezuela", country: "Venezuela"},
    { value: "Viet Nam", country: "Viet Nam"},
    { value: "Virgin Islands, British", country: "Virgin Islands, British"},
    { value: "Virgin Islands, U.S.", country: "Virgin Islands, U.S."},
    { value: "Wallis and Futuna", country: "Wallis and Futuna"},
    { value: "Western Sahara", country: "Western Sahara"},
    { value: "Yemen", country: "Yemen"},
    { value: "Zambia", country: "Zambia"},
    { value: "Zimbabwe", country: "Zimbabwe"}];
}

export default new DataStore();